import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

export default function Flashcards(){
 const [decks,setDecks]=useState([]),[selected,setSelected]=useState(null),[cards,setCards]=useState([]),[index,setIndex]=useState(0),[showAnswer,setShowAnswer]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let active=true; (async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const {data,error:e}=await supabase.from('flashcard_decks').select('*').eq('owner_id',user.id).order('created_at',{ascending:false});if(!active)return;if(e){console.error('Flashcard decks failed',e);setError(e.message)}setDecks(data||[]);setLoading(false)})();return()=>{active=false}},[])
 async function openDeck(deck){setSelected(deck);setIndex(0);setShowAnswer(false);const {data,error:e}=await supabase.from('flashcards').select('*').eq('deck_id',deck.id).order('created_at');if(e){console.error('Flashcards failed',e);setError(e.message);setCards([])}else setCards(data||[])}
 if(loading)return <div className="sv-page"><div className="sv-container">Loading flashcards…</div></div>
 return <div className="sv-page"><div className="sv-container" style={{paddingTop:34}}>{error&&<div className="sv-social-notice" onClick={()=>setError('')}>{error} ×</div>}
  <div className="sv-page-header"><div><p className="sv-section-label">Study smarter</p><h1>Flashcards</h1><p className="sv-page-subtitle">Review the decks you created in your study rooms.</p></div></div>
  {!selected?<div className="sv-card"><h2>Your decks</h2>{decks.length===0?<p className="sv-empty">No flashcard decks yet. Open a room and create one in Study Tools.</p>:<div style={{display:'grid',gap:12,marginTop:16}}>{decks.map(d=><button key={d.id} className="sv-card" style={{textAlign:'left',cursor:'pointer'}} onClick={()=>openDeck(d)}><strong>{d.title}</strong><p style={{marginTop:5,color:'var(--app-muted)'}}>{d.description||'Room study deck'} · View cards →</p></button>)}</div>}</div>
  :<div className="sv-card"><button onClick={()=>setSelected(null)} style={{background:'none',border:0,cursor:'pointer',padding:0,marginBottom:18}}>← All decks</button><p className="sv-section-label">{selected.title}</p>{cards.length===0?<p className="sv-empty">This deck has no cards yet.</p>:<><div style={{textAlign:'center',padding:'36px 20px',minHeight:180}}><p style={{color:'var(--app-muted)',fontSize:12}}>Card {index+1} of {cards.length}</p><h2 style={{marginTop:18}}>{showAnswer?cards[index].answer:cards[index].question}</h2><button className="sv-btn-primary" style={{marginTop:24}} onClick={()=>setShowAnswer(v=>!v)}>{showAnswer?'Show question':'Show answer'}</button></div><div style={{display:'flex',justifyContent:'space-between',gap:12}}><button disabled={index===0} onClick={()=>{setIndex(i=>i-1);setShowAnswer(false)}}>← Previous</button><button disabled={index===cards.length-1} onClick={()=>{setIndex(i=>i+1);setShowAnswer(false)}}>Next →</button></div></>}</div>}
 </div></div>
}
