import './Settings.css'
import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'

const themes=[{id:'cozy',emoji:'🌿',name:'Cozy',description:'Warm, calm and comfortable'},{id:'focused',emoji:'💼',name:'Focused',description:'Clean and distraction-free'},{id:'dark',emoji:'🌙',name:'Dark',description:'Low-light study workspace'},{id:'light',emoji:'☀️',name:'Light',description:'Bright and minimal'},{id:'custom',emoji:'🎨',name:'Custom',description:'A soft personalized palette'}]
const statuses=['Studying','Busy','Available','Away','Invisible']
export default function Settings(){
 const {user}=useAuth();const [params,setParams]=useSearchParams();const [section,setSection]=useState(params.get('section')||'profile');const [form,setForm]=useState({display_name:'',username:'',bio:'',study_goal:'',emoji_avatar:'👤',status:'Available',age_group:''});const [notifications,setNotifications]=useState({messages:true,friend_requests:true,room_invites:true,assignments:true,deadlines:true,reminders:true,weekly_reports:true,achievements:true});const [privacy,setPrivacy]=useState({show_online:true,allow_friend_requests:true,show_study_status:true});const [theme,setTheme]=useState('dark');const [avatarFile,setAvatarFile]=useState(null);const [rooms,setRooms]=useState([]);const [roomsLoading,setRoomsLoading]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('')
 useEffect(()=>{if(!user)return;const m=user.user_metadata||{};setForm({display_name:m.display_name||user.email?.split('@')[0]||'',username:m.username||'',bio:m.bio||'',study_goal:m.study_goal||'',emoji_avatar:m.emoji_avatar||'👤',status:m.status||'Available',age_group:m.age_group||''});setTheme(m.appearance||m.study_experience||localStorage.getItem('studyverse-theme')||'dark');setNotifications(current=>({...current,...(m.notifications||{})}));setPrivacy(current=>({...current,...(m.privacy||{})}))},[user?.id])
 useEffect(()=>{if(section==='room_history'&&user)fetchRoomHistory()},[section,user?.id])
 async function fetchRoomHistory(){setRoomsLoading(true);setError('');const {data,error:fetchError}=await supabase.from('room_history').select('*').eq('host_id',user.id).order('created_at',{ascending:false});if(fetchError)setError(`Room history could not be loaded: ${fetchError.message}`);setRooms(data||[]);setRoomsLoading(false)}
 function selectSection(value){setSection(value);setParams({section:value});setMessage('');setError('')}
 async function saveProfile(event){event.preventDefault();setSaving(true);setMessage('');setError('');let avatar_url=user.user_metadata?.avatar_url||'';if(avatarFile){const ext=avatarFile.name.split('.').pop()||'jpg',path=`${user.id}/profile-${Date.now()}.${ext}`;const {error:uploadError}=await supabase.storage.from('avatars').upload(path,avatarFile,{upsert:true});if(uploadError){setError(`Profile picture could not be uploaded: ${uploadError.message}`);setSaving(false);return}const {data}=supabase.storage.from('avatars').getPublicUrl(path);avatar_url=data.publicUrl}const {error:updateError}=await supabase.auth.updateUser({data:{...form,avatar_url}});if(updateError)setError(updateError.message);else{setMessage('Profile saved successfully.');setAvatarFile(null)}setSaving(false)}
 async function savePreference(key,value){const {error:updateError}=await supabase.auth.updateUser({data:{[key]:value}});if(updateError)setError(updateError.message);else setMessage('Preference saved.')}
 async function changeTheme(id){setTheme(id);document.documentElement.dataset.theme=id;localStorage.setItem('studyverse-theme',id);const {error:updateError}=await supabase.auth.updateUser({data:{appearance:id,study_experience:id}});if(updateError)setError(updateError.message);else setMessage(`${themes.find(t=>t.id===id)?.name} appearance applied.`)}
 return <div className="sv-page"><div className="sv-container sv-settings-page"><div className="sv-page-header"><div><p className="sv-eyebrow">Preferences</p><h1>Settings</h1><p className="sv-eyebrow" style={{marginTop:8}}>Manage your profile, appearance, notifications, privacy and room history.</p></div></div><div className="sv-settings-layout"><aside className="sv-settings-nav sv-card">{[['profile','👤','Profile'],['appearance','🎨','Appearance'],['notifications','🔔','Notifications'],['privacy','🔒','Privacy'],['room_history','🗂️','Room History'],['account','⚙️','Account']].map(([id,icon,label])=><button key={id} className={section===id?'active':''} onClick={()=>selectSection(id)}>{icon}<span>{label}</span></button>)}</aside><section className="sv-settings-content">
 {section==='profile'&&<form className="sv-card sv-settings-card" onSubmit={saveProfile}><div className="sv-settings-card-title"><div><h2>Edit Profile</h2><p>Personalize how people see you across StudyVerse.</p></div></div><div className="sv-profile-editor-head"><div className="sv-profile-avatar-preview">{user.user_metadata?.avatar_url?<img src={user.user_metadata.avatar_url} alt="Profile"/>:form.emoji_avatar}</div><label className="sv-upload-button">Choose picture<input type="file" accept="image/*" onChange={e=>setAvatarFile(e.target.files?.[0]||null)}/></label></div><div className="sv-form-grid"><label>Display Name<input value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})} placeholder="Your name"/></label><label>Username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value.replace(/\s/g,'').toLowerCase()})} placeholder="yourusername"/></label><label>Study Goal<input value={form.study_goal} onChange={e=>setForm({...form,study_goal:e.target.value})} placeholder="e.g. Study 2 hours daily"/></label><label>Age Group<select value={form.age_group} onChange={e=>setForm({...form,age_group:e.target.value})}><option value="">Prefer not to say</option><option value="13-17">13–17</option><option value="18-24">18–24</option><option value="25-34">25–34</option><option value="35-44">35–44</option><option value="45+">45+</option></select></label><label>Emoji Avatar<select value={form.emoji_avatar} onChange={e=>setForm({...form,emoji_avatar:e.target.value})}>{['👤','📚','🧠','🌿','☕','🌙','✨','🎧','📝','💻'].map(e=><option key={e}>{e}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></div><label>Bio<textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} rows="4" maxLength="180" placeholder="Tell your study circle a little about you"/></label><div className="sv-settings-actions"><button className="sv-primary-button" disabled={saving}>{saving?'Saving...':'Save Profile'}</button></div></form>}
 {section==='appearance'&&<div className="sv-card sv-settings-card"><div className="sv-settings-card-title"><div><h2>Appearance</h2><p>Choose the visual atmosphere you want for StudyVerse.</p></div></div><div className="sv-theme-grid">{themes.map(t=><button type="button" key={t.id} className={`sv-theme-option ${theme===t.id?'selected':''}`} onClick={()=>changeTheme(t.id)}><span className={`sv-theme-preview ${t.id}`}>{t.emoji}</span><strong>{t.name}</strong><small>{t.description}</small>{theme===t.id&&<b>Selected</b>}</button>)}</div><div className="sv-preference-note">You can change this anytime from the profile menu.</div></div>}
 {section==='notifications'&&<div className="sv-card sv-settings-card"><div className="sv-settings-card-title"><div><h2>Notifications</h2><p>Choose which StudyVerse updates you want to receive.</p></div></div><div className="sv-toggle-list">{Object.entries({messages:'Messages',friend_requests:'Friend requests',room_invites:'Room invites',assignments:'Assignments',deadlines:'Task deadlines',reminders:'Study reminders',weekly_reports:'Weekly reports',achievements:'Achievements'}).map(([key,label])=><label key={key}><span>{label}</span><input type="checkbox" checked={!!notifications[key]} onChange={e=>{const next={...notifications,[key]:e.target.checked};setNotifications(next);savePreference('notifications',next)}}/></label>)}</div></div>}
 {section==='privacy'&&<div className="sv-card sv-settings-card"><div className="sv-settings-card-title"><div><h2>Privacy</h2><p>Control what other students can see about you.</p></div></div><div className="sv-toggle-list">{Object.entries({show_online:'Show when I am online',allow_friend_requests:'Allow friend requests',show_study_status:'Show my study status'}).map(([key,label])=><label key={key}><span>{label}</span><input type="checkbox" checked={!!privacy[key]} onChange={e=>{const next={...privacy,[key]:e.target.checked};setPrivacy(next);savePreference('privacy',next)}}/></label>)}</div></div>}
 {section==='room_history'&&<div className="sv-card sv-settings-card"><div className="sv-settings-card-title"><div><h2>Room History</h2><p>Every private room you create is saved here for future reference.</p></div><button type="button" className="sv-btn-ghost" onClick={fetchRoomHistory}>↻ Refresh</button></div>{roomsLoading?<div className="sv-history-empty">Loading your room history...</div>:rooms.length===0?<div className="sv-history-empty">You haven't created a room yet. Your created rooms will appear here automatically.</div>:<div className="sv-room-history-list">{rooms.map(room=><div className="sv-room-history-item" key={room.id}><div><strong>{room.room_name}</strong><span>Created {new Date(room.created_at).toLocaleString()}</span></div><div className="sv-room-history-code"><small>Room code</small><b>{room.room_code}</b></div></div>)}</div>}</div>}
 {section==='account'&&<div className="sv-card sv-settings-card"><div className="sv-settings-card-title"><div><h2>Account</h2><p>Your StudyVerse account information.</p></div></div><div className="sv-account-row"><span>Email</span><strong>{user.email}</strong></div><div className="sv-account-row"><span>Account created</span><strong>{user.created_at?new Date(user.created_at).toLocaleDateString():'—'}</strong></div></div>}
 {message&&<div className="sv-settings-message">✓ {message}</div>}{error&&<div className="sv-settings-error">⚠ {error}</div>}</section></div></div></div>
}
