import { useEffect, useState, useRef } from 'react'
import { supabase } from '../lib/supabase'

const STATUS_ICON={studying:'🟢',break:'🟡',offline:'⚫'}
function formatTime(s){return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function formatMessageTime(value){return new Date(value).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}

export default function RoomView({roomId,userId,onLeft}){
 const [room,setRoom]=useState(null),[members,setMembers]=useState([]),[messages,setMessages]=useState([]),[messageInput,setMessageInput]=useState(''),[elapsed,setElapsed]=useState(0),[subjectInput,setSubjectInput]=useState(''),[loading,setLoading]=useState(true),[chatLoading,setChatLoading]=useState(true)
 const tickRef=useRef(null),chatEndRef=useRef(null)
 useEffect(()=>{fetchRoom();fetchMembers();fetchMessages()},[roomId])
 async function fetchRoom(){const {data,error}=await supabase.from('study_rooms').select('*').eq('id',roomId).single();if(error)console.error(error);setRoom(data);setLoading(false)}
 async function fetchMembers(){const {data,error}=await supabase.from('room_members').select('*').eq('room_id',roomId).order('joined_at',{ascending:true});if(error)console.error(error);setMembers(data||[])}
 async function fetchMessages(){setChatLoading(true);const {data,error}=await supabase.from('room_messages').select('id,room_id,user_id,display_name,message,sender_id,body,created_at').eq('room_id',roomId).order('created_at',{ascending:true}).limit(200);if(error)console.error(error);setMessages(data||[]);setChatLoading(false)}
 useEffect(()=>{const channel=supabase.channel(`room-${roomId}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'study_rooms',filter:`id=eq.${roomId}`},p=>setRoom(p.new)).on('postgres_changes',{event:'*',schema:'public',table:'room_members',filter:`room_id=eq.${roomId}`},p=>setMembers(prev=>p.eventType==='INSERT'?[...prev,p.new]:p.eventType==='UPDATE'?prev.map(m=>m.id===p.new.id?p.new:m):p.eventType==='DELETE'?prev.filter(m=>m.id!==p.old.id):prev)).on('postgres_changes',{event:'INSERT',schema:'public',table:'room_messages',filter:`room_id=eq.${roomId}`},p=>setMessages(prev=>prev.some(m=>m.id===p.new.id)?prev:[...prev,p.new])).subscribe();return()=>supabase.removeChannel(channel)},[roomId])
 useEffect(()=>{chatEndRef.current?.scrollIntoView({behavior:'smooth'})},[messages.length])
 useEffect(()=>{clearInterval(tickRef.current);if(room?.timer_status==='running'&&room?.timer_started_at){const start=new Date(room.timer_started_at).getTime();tickRef.current=setInterval(()=>setElapsed(Math.floor((Date.now()-start)/1000)),1000)}else setElapsed(0);return()=>clearInterval(tickRef.current)},[room?.timer_status,room?.timer_started_at])
 const isHost=room?.host_id===userId,isRunning=room?.timer_status==='running'
 async function startSession(){const {error}=await supabase.from('study_rooms').update({timer_status:'running',timer_started_at:new Date().toISOString(),current_subject:subjectInput||'General Study'}).eq('id',roomId);if(error)alert(error.message)}
 async function endSession(){if(!room?.timer_started_at)return;const startedAt=room.timer_started_at,endedAt=new Date().toISOString(),durationSeconds=Math.floor((new Date(endedAt)-new Date(startedAt))/1000);if(durationSeconds<=0)return;const studyingMembers=members.filter(m=>m.status==='studying'),xpEarned=Math.floor(durationSeconds/60)*2;if(studyingMembers.length){const {error}=await supabase.from('room_sessions').insert(studyingMembers.map(m=>({room_id:roomId,user_id:m.user_id,subject:room.current_subject,started_at:startedAt,ended_at:endedAt,duration_seconds:durationSeconds,xp_earned:xpEarned})));if(error)alert(error.message)}const {error}=await supabase.from('study_rooms').update({timer_status:'idle',timer_started_at:null}).eq('id',roomId);if(error)alert(error.message)}
 async function setMyStatus(status){const {error}=await supabase.from('room_members').update({status}).eq('room_id',roomId).eq('user_id',userId);if(error)alert(error.message)}
 async function sendMessage(){
  const text=messageInput.trim();if(!text||!userId)return
  const me=members.find(m=>m.user_id===userId),displayName=me?.display_name||'StudyVerse member'
  const {data:inserted,error}=await supabase.from('room_messages').insert({room_id:roomId,user_id:userId,display_name:displayName,message:text,sender_id:userId,body:text}).select('id').single()
  if(error){alert(error.message);return}
  setMessageInput('')
  const recipients=members.filter(m=>m.user_id!==userId).map(m=>({user_id:m.user_id,type:'message',title:`${displayName} sent a room message`,message:text.slice(0,180),link:'/rooms',actor_id:userId,metadata:{room_id:roomId,room_name:room?.room_name||'',message_id:inserted?.id||null}}))
  if(recipients.length){const {error:notificationError}=await supabase.from('notifications').insert(recipients);if(notificationError)console.error('Room message notification failed:',notificationError.message)}
 }
 async function leaveRoom(){await supabase.from('room_members').delete().eq('room_id',roomId).eq('user_id',userId);onLeft?.()}
 if(loading||!room)return <div className="sv-card" style={{textAlign:'center',color:'var(--app-muted)'}}>Loading room...</div>
 return <div>
  <div style={s.header}><div><p style={s.label}>Study Room</p><h1 style={s.title}>{room.room_name}</h1><p style={s.subtitle}>Private focus space · {members.length} of {room.max_members} members</p></div><div style={s.code}><span>Room code</span><strong>{room.room_code}</strong></div></div>
  <div className="sv-card"><p className="sv-section-label">Members</p><div style={s.list}>{members.map(m=><div key={m.id} style={s.member}><div style={s.memberLeft}><span style={{fontSize:18}}>{m.user_id===room.host_id?'●':'○'}</span><span>{m.display_name}</span></div><span className="sv-badge">{STATUS_ICON[m.status]||'⚫'} {m.status}</span></div>)}</div></div>
  <div className="sv-card" style={s.timer}><p className="sv-section-label">Shared Study Session · {room.current_subject||'General Study'}</p><div style={{...s.clock,color:isRunning?'var(--app-accent)':'var(--app-muted)'}}>{formatTime(elapsed)}</div><p style={s.status}>{isRunning?'Session in progress':'Ready when you are'}</p>{isHost?(isRunning?<button onClick={endSession} style={s.full}>End Session</button>:<div style={s.start}><input placeholder="Subject (optional)" value={subjectInput} onChange={e=>setSubjectInput(e.target.value)}/><button onClick={startSession}>Start Session</button></div>):<p style={s.hint}>Only the room host can start or end the shared session.</p>}</div>
  <div className="sv-card" style={s.chatCard}><div style={s.chatHeader}><div><p className="sv-section-label" style={{marginBottom:3}}>Room Chat</p><span style={s.chatSub}>Messages are saved for this room.</span></div><span style={s.chatCount}>{messages.length}</span></div><div style={s.chatMessages}>{chatLoading?<p style={s.empty}>Loading messages...</p>:messages.length===0?<p style={s.empty}>No messages yet. Say hi to your study group 👋</p>:messages.map(m=>{const senderId=m.user_id||m.sender_id,mine=senderId===userId,sender=members.find(x=>x.user_id===senderId),text=m.message||m.body||'',displayName=m.display_name||sender?.display_name||'StudyVerse member';return <div key={m.id} style={{...s.messageRow,justifyContent:mine?'flex-end':'flex-start'}}><div style={{...s.messageBubble,...(mine?s.mine:{})}}><div style={s.messageMeta}>{mine?'You':displayName} · {formatMessageTime(m.created_at)}</div><div>{text}</div></div></div>})}<div ref={chatEndRef}/></div><div style={s.chatComposer}><input value={messageInput} onChange={e=>setMessageInput(e.target.value)} placeholder="Message your study group..." maxLength={4000} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}}}/><button onClick={sendMessage} disabled={!messageInput.trim()}>Send</button></div></div>
  <div className="sv-card"><p className="sv-section-label">My Status</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button onClick={()=>setMyStatus('studying')}>🟢 Studying</button><button onClick={()=>setMyStatus('break')}>🟡 Break</button></div></div>
  <button onClick={leaveRoom} style={s.leave}>Leave Room</button>
 </div>
}
const s={header:{display:'flex',justifyContent:'space-between',alignItems:'flex-start',flexWrap:'wrap',gap:16,marginBottom:24},label:{fontSize:13,color:'var(--app-muted)',marginBottom:5,fontWeight:600},title:{fontSize:28,fontWeight:700,color:'var(--app-text)',lineHeight:1.2},subtitle:{marginTop:7,fontSize:13,color:'var(--app-muted)'},code:{textAlign:'center',background:'var(--app-accent-soft)',border:'1px solid var(--app-border)',borderRadius:12,padding:'10px 18px',minWidth:120},list:{display:'flex',flexDirection:'column',gap:8,marginTop:12},member:{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'12px 14px',background:'var(--app-accent-soft)',borderRadius:10},memberLeft:{display:'flex',alignItems:'center',gap:10,fontWeight:600,color:'var(--app-text)'},timer:{textAlign:'center',padding:'32px 24px'},clock:{fontSize:52,fontWeight:700,letterSpacing:4,padding:'16px 0',fontVariantNumeric:'tabular-nums'},status:{fontSize:13,color:'var(--app-muted)',marginBottom:18},start:{display:'flex',gap:10,justifyContent:'center',flexWrap:'wrap'},full:{width:'100%'},hint:{fontSize:13,color:'var(--app-muted)'},chatCard:{padding:0,overflow:'hidden',marginTop:16},chatHeader:{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'18px 20px',borderBottom:'1px solid var(--app-border)'},chatSub:{fontSize:12,color:'var(--app-muted)'},chatCount:{fontSize:12,color:'var(--app-muted)',background:'var(--app-accent-soft)',padding:'5px 9px',borderRadius:99},chatMessages:{height:330,overflowY:'auto',padding:'18px 20px',display:'flex',flexDirection:'column',gap:9},empty:{textAlign:'center',color:'var(--app-muted)',fontSize:13,margin:'auto'},messageRow:{display:'flex'},messageBubble:{maxWidth:'78%',padding:'9px 12px',borderRadius:12,background:'var(--app-accent-soft)',color:'var(--app-text)',fontSize:13,lineHeight:1.5},mine:{background:'var(--app-accent)',color:'#fff'},messageMeta:{fontSize:10,opacity:.7,marginBottom:3},chatComposer:{display:'flex',gap:9,padding:'12px 14px',borderTop:'1px solid var(--app-border)'},leave:{marginTop:4,background:'transparent',border:'1px solid rgba(200,70,70,.35)',color:'#b94b4b',borderRadius:10,padding:'10px 16px'}}
