import { lazy, Suspense, useEffect } from 'react'
import { Routes, Route, useLocation } from 'react-router-dom'
import './themes.css'
import ProtectedRoute from './components/ProtectedRoute'
import Sidebar from './components/Sidebar'
import ProfileMenu from './components/ProfileMenu'
import Onboarding from './components/Onboarding'
import EmailVerificationBanner from './components/EmailVerificationBanner'
import { useAuth } from './context/AuthContext'

const Dashboard=lazy(()=>import('./pages/Dashboard'));const Subjects=lazy(()=>import('./pages/Subjects'));const Timer=lazy(()=>import('./pages/Timer'));const Tasks=lazy(()=>import('./pages/Tasks'));const Analytics=lazy(()=>import('./pages/Analytics'));const Rooms=lazy(()=>import('./pages/Rooms'));const Friends=lazy(()=>import('./pages/Friends'));const Settings=lazy(()=>import('./pages/Settings'));const Calendar=lazy(()=>import('./pages/Calendar'));const Flashcards=lazy(()=>import('./pages/Flashcards'));const Placeholder=lazy(()=>import('./pages/Placeholder'));const Login=lazy(()=>import('./pages/Login'));const Signup=lazy(()=>import('./pages/Signup'));const ForgotPassword=lazy(()=>import('./pages/ForgotPassword'));const ResetPassword=lazy(()=>import('./pages/ResetPassword'))

function ThemeManager({user}){useEffect(()=>{const theme=user?.user_metadata?.appearance||localStorage.getItem('studyverse-theme')||'light';document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme==='dark'?'dark':'light';localStorage.setItem('studyverse-theme',theme)},[user?.user_metadata?.appearance]);return null}
function Loading(){return <div className="sv-page sv-container"><div className="sv-card" style={{padding:24}}>Loading StudyVerse…</div></div>}
function AppShell({children}){const {pathname}=useLocation();const {user}=useAuth();const authPage=['/login','/signup','/forgot-password','/reset-password'].includes(pathname);const needsOnboarding=Boolean(user&&user.user_metadata?.onboarding_completed!==true);return <><ThemeManager user={user}/>{authPage?children:<div className="sv-app-shell"><Sidebar/><main className="sv-main"><EmailVerificationBanner/><header className="sv-topbar"><div className="sv-topbar-spacer"/><ProfileMenu/></header>{children}</main>{needsOnboarding&&<Onboarding onComplete={()=>window.location.reload()}/>}</div>}</>}
function App(){return <AppShell><Suspense fallback={<Loading/>}><Routes><Route path="/login" element={<Login/>}/><Route path="/signup" element={<Signup/>}/><Route path="/forgot-password" element={<ForgotPassword/>}/><Route path="/reset-password" element={<ResetPassword/>}/><Route path="/" element={<ProtectedRoute><Dashboard/></ProtectedRoute>}/><Route path="/dashboard" element={<ProtectedRoute><Dashboard/></ProtectedRoute>}/><Route path="/subjects" element={<ProtectedRoute><Subjects/></ProtectedRoute>}/><Route path="/timer" element={<ProtectedRoute><Timer/></ProtectedRoute>}/><Route path="/tasks" element={<ProtectedRoute><Tasks/></ProtectedRoute>}/><Route path="/analytics" element={<ProtectedRoute><Analytics/></ProtectedRoute>}/><Route path="/rooms" element={<ProtectedRoute><Rooms/></ProtectedRoute>}/><Route path="/friends" element={<ProtectedRoute><Friends/></ProtectedRoute>}/><Route path="/settings" element={<ProtectedRoute><Settings/></ProtectedRoute>}/><Route path="/calendar" element={<ProtectedRoute><Calendar/></ProtectedRoute>}/><Route path="/flashcards" element={<ProtectedRoute><Flashcards/></ProtectedRoute>}/><Route path="/resources" element={<ProtectedRoute><Placeholder title="Resources" icon="📚" description="Keep your study materials organized and easy to access."/></ProtectedRoute>}/><Route path="/support" element={<ProtectedRoute><Placeholder title="Support" icon="💬" description="Get help with StudyVerse and your study workspace."/></ProtectedRoute>}/><Route path="*" element={<ProtectedRoute><Dashboard/></ProtectedRoute>}/></Routes></Suspense></AppShell>}
export default App
